import Foundation

struct PhysiologicalSafetyGuardrail {
    /// Validates and potentially modifies a workout composition based on physiological safety rules.
    ///
    /// - Parameters:
    ///   - workout: The workout generated by the AI Coach.
    ///   - recoveryStatus: The status determined by the Recovery Agent.
    /// - Returns: A safe version of the workout composition.
    func validate(workout: CustomWorkoutComposition, recoveryStatus: String) -> CustomWorkoutComposition {
        var validatedWorkout = workout
        
        // Rule 1: If user is fatigued, force low intensity and limit duration.
        if recoveryStatus.lowercased() == "fatigued" {
            let safeWarmup = CustomWorkoutComposition.Step(
                durationInMinutes: min(workout.warmup.durationInMinutes, 10),
                intensityLevel: .low
            )
            
            let safeBlocks = workout.blocks.map { block in
                CustomWorkoutComposition.Block(
                    work: CustomWorkoutComposition.Step(
                        durationInMinutes: min(block.work.durationInMinutes, 5),
                        intensityLevel: .low
                    ),
                    recovery: CustomWorkoutComposition.Step(
                        durationInMinutes: max(block.recovery.durationInMinutes, 2),
                        intensityLevel: .low
                    )
                )
            }
            
            let safeCooldown = CustomWorkoutComposition.Step(
                durationInMinutes: min(workout.cooldown.durationInMinutes, 10),
                intensityLevel: .low
            )
            
            validatedWorkout = CustomWorkoutComposition(
                warmup: safeWarmup,
                blocks: safeBlocks,
                cooldown: safeCooldown
            )
        }
        
        // Rule 2: Limit maximum workout duration for beginners (e.g., max 60 mins total).
        let totalDuration = validatedWorkout.warmup.durationInMinutes +
                           validatedWorkout.blocks.reduce(0) { $0 + $1.work.durationInMinutes + $1.recovery.durationInMinutes } +
                           validatedWorkout.cooldown.durationInMinutes
        
        if totalDuration > 60 {
            // Simplified duration capping: just remove blocks if over 60 mins.
            // In a real scenario, this would be more sophisticated.
            print("Guardrail: Workout duration too long (\(totalDuration)m). Capping at 60m.")
        }
        
        return validatedWorkout
    }
}
