import Foundation

struct PhysiologicalSafetyGuardrail {
    /// Validates and potentially modifies a workout composition based on physiological safety rules.
    ///
    /// - Parameters:
    ///   - workout: The workout generated by the AI Coach.
    ///   - recoveryStatus: The status determined by the Recovery Agent.
    ///   - loadStatus: The status determined by the Load Agent.
    /// - Returns: A safe version of the workout composition.
    func validate(
        workout: CustomWorkoutComposition,
        recoveryStatus: String,
        loadStatus: String
    ) -> CustomWorkoutComposition {
        var validatedWorkout = workout
        
        validatedWorkout = applyFatigueRule(workout: validatedWorkout, recoveryStatus: recoveryStatus)
        validatedWorkout = applyOverreachingRule(workout: validatedWorkout, loadStatus: loadStatus)
        validatedWorkout = applyDurationCapRule(workout: validatedWorkout)
        
        return validatedWorkout
    }
    
    private func applyFatigueRule(workout: CustomWorkoutComposition, recoveryStatus: String) -> CustomWorkoutComposition {
        guard recoveryStatus.lowercased() == "fatigued" else { return workout }
        
        let safeWarmup = CustomWorkoutComposition.Step(
            durationInMinutes: min(workout.warmup.durationInMinutes, 10),
            intensityLevel: .low
        )
        
        let safeBlocks = workout.blocks.map { block in
            CustomWorkoutComposition.Block(
                work: CustomWorkoutComposition.Step(
                    durationInMinutes: min(block.work.durationInMinutes, 5),
                    intensityLevel: .low
                ),
                recovery: CustomWorkoutComposition.Step(
                    durationInMinutes: max(block.recovery.durationInMinutes, 2),
                    intensityLevel: .low
                )
            )
        }
        
        let safeCooldown = CustomWorkoutComposition.Step(
            durationInMinutes: min(workout.cooldown.durationInMinutes, 10),
            intensityLevel: .low
        )
        
        return CustomWorkoutComposition(
            warmup: safeWarmup,
            blocks: safeBlocks,
            cooldown: safeCooldown
        )
    }
    
    private func applyOverreachingRule(workout: CustomWorkoutComposition, loadStatus: String) -> CustomWorkoutComposition {
        guard loadStatus.lowercased() == "overreaching" else { return workout }
        
        let safeBlocks = workout.blocks.map { block -> CustomWorkoutComposition.Block in
            let newIntensity: WorkoutIntensity = block.work.intensityLevel == .high ? .moderate : (block.work.intensityLevel ?? .low)
            return CustomWorkoutComposition.Block(
                work: CustomWorkoutComposition.Step(
                    durationInMinutes: min(block.work.durationInMinutes, 8),
                    intensityLevel: newIntensity
                ),
                recovery: block.recovery
            )
        }
        
        return CustomWorkoutComposition(
            warmup: workout.warmup,
            blocks: safeBlocks,
            cooldown: workout.cooldown
        )
    }
    
    private func applyDurationCapRule(workout: CustomWorkoutComposition) -> CustomWorkoutComposition {
        var validatedWorkout = workout
        var totalDuration = validatedWorkout.warmup.durationInMinutes +
                           validatedWorkout.blocks.reduce(0) { $0 + $1.work.durationInMinutes + $1.recovery.durationInMinutes } +
                           validatedWorkout.cooldown.durationInMinutes
        
        guard totalDuration > 60 else { return workout }
        
        print("Guardrail: Workout duration too long (\(totalDuration)m). Capping at 60m.")
        var adjustedBlocks = validatedWorkout.blocks
        
        while totalDuration > 60 && !adjustedBlocks.isEmpty {
            if adjustedBlocks.count > 1 {
                let removed = adjustedBlocks.removeLast()
                totalDuration -= (removed.work.durationInMinutes + removed.recovery.durationInMinutes)
            } else {
                // Only one block left, cap its duration to fit within 60 minutes
                let overage = totalDuration - 60
                let block = adjustedBlocks[0]
                let newWorkDuration = max(block.work.durationInMinutes - overage, 5)
                adjustedBlocks[0] = CustomWorkoutComposition.Block(
                    work: CustomWorkoutComposition.Step(
                        durationInMinutes: newWorkDuration,
                        intensityLevel: block.work.intensityLevel
                    ),
                    recovery: block.recovery
                )
                totalDuration = validatedWorkout.warmup.durationInMinutes + newWorkDuration + block.recovery.durationInMinutes + validatedWorkout.cooldown.durationInMinutes
                
                if totalDuration > 60 {
                    let finalOverage = totalDuration - 60
                    let newWarmup = max(validatedWorkout.warmup.durationInMinutes - (finalOverage / 2), 5)
                    let newCooldown = max(validatedWorkout.cooldown.durationInMinutes - (finalOverage - (finalOverage / 2)), 5)
                    validatedWorkout = CustomWorkoutComposition(
                        warmup: CustomWorkoutComposition.Step(
                            durationInMinutes: newWarmup,
                            intensityLevel: validatedWorkout.warmup.intensityLevel
                        ),
                        blocks: adjustedBlocks,
                        cooldown: CustomWorkoutComposition.Step(
                            durationInMinutes: newCooldown,
                            intensityLevel: validatedWorkout.cooldown.intensityLevel
                        )
                    )
                    totalDuration = newWarmup + newWorkDuration + block.recovery.durationInMinutes + newCooldown
                }
                break
            }
        }
        
        if totalDuration <= 60 {
            validatedWorkout = CustomWorkoutComposition(
                warmup: validatedWorkout.warmup,
                blocks: adjustedBlocks,
                cooldown: validatedWorkout.cooldown
            )
        }
        
        return validatedWorkout
    }
}
